{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25665",
  "id": 1359938114,
  "node_id": "I_kwDOAOvK985RDwJC",
  "number": 25665,
  "title": "ethminer can't find mining work in geth's rpc(8545)",
  "user": {
    "login": "zhongdonglin",
    "id": 44593101,
    "node_id": "MDQ6VXNlcjQ0NTkzMTAx",
    "avatar_url": "https://avatars.githubusercontent.com/u/44593101?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/zhongdonglin",
    "html_url": "https://github.com/zhongdonglin",
    "followers_url": "https://api.github.com/users/zhongdonglin/followers",
    "following_url": "https://api.github.com/users/zhongdonglin/following{/other_user}",
    "gists_url": "https://api.github.com/users/zhongdonglin/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/zhongdonglin/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/zhongdonglin/subscriptions",
    "organizations_url": "https://api.github.com/users/zhongdonglin/orgs",
    "repos_url": "https://api.github.com/users/zhongdonglin/repos",
    "events_url": "https://api.github.com/users/zhongdonglin/events{/privacy}",
    "received_events_url": "https://api.github.com/users/zhongdonglin/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 268304226,
      "node_id": "MDU6TGFiZWwyNjgzMDQyMjY=",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:docs",
      "name": "type:docs",
      "color": "fef2c0",
      "default": false,
      "description": null
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2022-09-02T09:27:13Z",
  "updated_at": "2022-09-02T14:53:06Z",
  "closed_at": null,
  "author_association": "NONE",
  "active_lock_reason": null,
  "body": "state:\r\n     start gethï¼š nohup geth --datadir data --http --http.addr 0.0.0.0 --http.api eth --miner.etherbase  ****** & > nohup.out\r\n     start ethminer:    nohup ./ethminer -v 9 -U -P http://127.0.0.1:8545 & > nohup.out\r\n\r\nquestion:\r\n     ethminer log print:\r\n          `ethminer 0.18.0\r\nBuild: linux/release/gnu\r\n\r\n i 09:26:21 ethminer Configured pool 127.0.0.1:8545\r\n i 09:26:21 ethminer Selected pool 127.0.0.1:8545\r\n i 09:26:21 ethminer Established connection to 127.0.0.1:8545\r\n i 09:26:21 ethminer Spinning up miners...\r\n i 09:26:21 ethminer  >> {\"id\":1,\"jsonrpc\":\"2.0\",\"method\":\"eth_getWork\",\"params\":[]}\r\ncu 09:26:21 cuda-0   Using Pci Id : 01:00.0 NVIDIA GeForce RTX 3090 (Compute 8.6) Memory : 23.70 GB\r\n i 09:26:21 ethminer  << {\"jsonrpc\":\"2.0\",\"id\":1,\"error\":{\"code\":-32000,\"message\":\"no mining work available yet\"}}\r\n X 09:26:21 ethminer Got code:-32000 message:no mining work available yet  from 127.0.0.1:8545\r\n`\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1235397008",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25665#issuecomment-1235397008",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665",
    "id": 1235397008,
    "node_id": "IC_kwDOAOvK985JoqmQ",
    "user": {
      "login": "rjl493456442",
      "id": 5959481,
      "node_id": "MDQ6VXNlcjU5NTk0ODE=",
      "avatar_url": "https://avatars.githubusercontent.com/u/5959481?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/rjl493456442",
      "html_url": "https://github.com/rjl493456442",
      "followers_url": "https://api.github.com/users/rjl493456442/followers",
      "following_url": "https://api.github.com/users/rjl493456442/following{/other_user}",
      "gists_url": "https://api.github.com/users/rjl493456442/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/rjl493456442/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/rjl493456442/subscriptions",
      "organizations_url": "https://api.github.com/users/rjl493456442/orgs",
      "repos_url": "https://api.github.com/users/rjl493456442/repos",
      "events_url": "https://api.github.com/users/rjl493456442/events{/privacy}",
      "received_events_url": "https://api.github.com/users/rjl493456442/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-02T11:42:58Z",
    "updated_at": "2022-09-02T11:42:58Z",
    "author_association": "MEMBER",
    "body": "You node just started and nothing is passed as the sealing task. So no mining work generated yet.\r\nYou can wait a bit and confirm that your node is synced.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1235397008/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1235598307",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25665#issuecomment-1235598307",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25665",
    "id": 1235598307,
    "node_id": "IC_kwDOAOvK985Jpbvj",
    "user": {
      "login": "zhongdonglin",
      "id": 44593101,
      "node_id": "MDQ6VXNlcjQ0NTkzMTAx",
      "avatar_url": "https://avatars.githubusercontent.com/u/44593101?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/zhongdonglin",
      "html_url": "https://github.com/zhongdonglin",
      "followers_url": "https://api.github.com/users/zhongdonglin/followers",
      "following_url": "https://api.github.com/users/zhongdonglin/following{/other_user}",
      "gists_url": "https://api.github.com/users/zhongdonglin/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/zhongdonglin/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/zhongdonglin/subscriptions",
      "organizations_url": "https://api.github.com/users/zhongdonglin/orgs",
      "repos_url": "https://api.github.com/users/zhongdonglin/repos",
      "events_url": "https://api.github.com/users/zhongdonglin/events{/privacy}",
      "received_events_url": "https://api.github.com/users/zhongdonglin/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-02T14:53:06Z",
    "updated_at": "2022-09-02T14:53:06Z",
    "author_association": "NONE",
    "body": "ou....geth has been synced to the latest block of the chain.I started ethminer after the sync is complete",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1235598307/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
