{
  "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679",
  "repository_url": "https://api.github.com/repos/ethereum/go-ethereum",
  "labels_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679/labels{/name}",
  "comments_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679/comments",
  "events_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679/events",
  "html_url": "https://github.com/ethereum/go-ethereum/issues/25679",
  "id": 1361287343,
  "node_id": "I_kwDOAOvK985RI5iv",
  "number": 25679,
  "title": "Failed to update chain markers",
  "user": {
    "login": "miguelmota",
    "id": 168240,
    "node_id": "MDQ6VXNlcjE2ODI0MA==",
    "avatar_url": "https://avatars.githubusercontent.com/u/168240?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/miguelmota",
    "html_url": "https://github.com/miguelmota",
    "followers_url": "https://api.github.com/users/miguelmota/followers",
    "following_url": "https://api.github.com/users/miguelmota/following{/other_user}",
    "gists_url": "https://api.github.com/users/miguelmota/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/miguelmota/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/miguelmota/subscriptions",
    "organizations_url": "https://api.github.com/users/miguelmota/orgs",
    "repos_url": "https://api.github.com/users/miguelmota/repos",
    "events_url": "https://api.github.com/users/miguelmota/events{/privacy}",
    "received_events_url": "https://api.github.com/users/miguelmota/received_events",
    "type": "User",
    "site_admin": false
  },
  "labels": [
    {
      "id": 72233650,
      "node_id": "MDU6TGFiZWw3MjIzMzY1MA==",
      "url": "https://api.github.com/repos/ethereum/go-ethereum/labels/type:bug",
      "name": "type:bug",
      "color": "FF5E5E",
      "default": false,
      "description": ""
    }
  ],
  "state": "open",
  "locked": false,
  "assignee": null,
  "assignees": [

  ],
  "milestone": null,
  "comments": 2,
  "created_at": "2022-09-05T00:04:57Z",
  "updated_at": "2022-09-05T09:12:18Z",
  "closed_at": null,
  "author_association": "CONTRIBUTOR",
  "active_lock_reason": null,
  "body": "Hi, any idea why this error occurs? can't seem to fully sync even after wiping storage and trying again. Thanks in advance\r\n\r\n```sh\r\nCRIT [09-05|00:00:02.054] Failed to update chain markers           error=\"leveldb/table: corruption on data-block (pos=182186521): checksum mismatch, want=0x23a5bb08 got=0xe7ce424c [file=001506.ldb]\"\r\n```\r\n\r\n#### System information\r\n\r\nGeth version: 1.10.23-stable\r\nOS & Version: Linux\r\n\r\n```sh\r\nGeth\r\nVersion: 1.10.23-stable\r\nGit Commit: d901d85377c2c2f05f09f423c7d739c0feecd90a\r\nGit Commit Date: 20220824\r\nArchitecture: amd64\r\nGo Version: go1.19\r\nOperating System: linux\r\nGOPATH=\r\nGOROOT=\r\n```\r\n\r\n```\r\nLinux intelnuc 5.19.6-arch1-1 #1 SMP PREEMPT_DYNAMIC Wed, 31 Aug 2022 22:09:40 +0000 x86_64 GNU/Linux\r\n```\r\n\r\n#### Expected behaviour\r\n\r\nNo error when initial syncing\r\n\r\n#### Actual behaviour\r\n\r\n\r\n```\r\nINFO [09-04|23:59:39.787] Merge configured:\r\nINFO [09-04|23:59:39.787]  - Hard-fork specification:    https://github.com/ethereum/execution-specs/blob/master/network-upgrades/mainnet-upgrades/paris.md\r\nINFO [09-04|23:59:39.787]  - Network known to be merged: false\r\nINFO [09-04|23:59:39.787]  - Total terminal difficulty:  58750000000000000000000\r\nINFO [09-04|23:59:39.787]  - Merge netsplit block:       <nil>\r\nINFO [09-04|23:59:39.787] ---------------------------------------------------------------------------------------------------------------------------------------------------------\r\nINFO [09-04|23:59:39.787]\r\nINFO [09-04|23:59:39.789] Disk storage enabled for ethash caches   dir=/root/.ethereum/geth/ethash count=3\r\nINFO [09-04|23:59:39.789] Disk storage enabled for ethash DAGs     dir=/root/.ethash               count=2\r\nINFO [09-04|23:59:39.789] Initialising Ethereum protocol           network=1 dbversion=8\r\nINFO [09-04|23:59:40.262] Loaded most recent local header          number=1,417,624 hash=4a173e..0b75dd td=16,083,127,554,052,015,996 age=6y5mo1w\r\nINFO [09-04|23:59:40.262] Loaded most recent local full block      number=0         hash=d4e567..cb8fa3 td=17,179,869,184             age=53y5mo1w\r\nINFO [09-04|23:59:40.262] Loaded most recent local fast block      number=0         hash=d4e567..cb8fa3 td=17,179,869,184             age=53y5mo1w\r\nERROR[09-04|23:59:40.262] Truncating ancient chain                 from=1,417,624 to=0\r\nWARN [09-04|23:59:40.262] Rewinding blockchain                     target=0\r\nCRIT [09-05|00:00:02.054] Failed to update chain markers           error=\"leveldb/table: corruption on data-block (pos=182186521): checksum mismatch, want=0x23a5bb08 got=0xe7ce424c [file=001506.ldb]\"\r\n```\r\n\r\n\r\n#### Steps to reproduce the behaviour\r\n\r\n```sh\r\ndocker run \\\r\n        --detach \\\r\n        --name geth \\\r\n        -it \\\r\n        --restart=unless-stopped \\\r\n        --network=\"host\" \\\r\n        --log-driver local \\\r\n        --log-opt max-size=2gb \\\r\n        -v /mnt/ssd/ethereum_geth:/root/.ethereum \\\r\n        -v $HOME/geth_jwt:/geth_jwt:ro \\\r\n        -p 30303:30303/tcp \\\r\n        -p 30303:30303/udp \\\r\n        -p 8545:8545 \\\r\n        ethereum/client-go:v1.10.23 \\\r\n        --http \\\r\n        --http.addr=\"0.0.0.0\" \\\r\n\t--http.api=eth,net,engine,admin \\\r\n        --http.vhosts=\"*\" \\\r\n        --ipcdisable \\\r\n\t--syncmode=\"full\" \\\r\n\t--authrpc.addr=\"0.0.0.0\" \\\r\n        --authrpc.vhosts=\"*\" \\\r\n\t--datadir=/root/.ethereum\r\n```\r\n\r\n\r\n#### Backtrace\r\n\r\n",
  "closed_by": null,
  "reactions": {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679/reactions",
    "total_count": 0,
    "+1": 0,
    "-1": 0,
    "laugh": 0,
    "hooray": 0,
    "confused": 0,
    "heart": 0,
    "rocket": 0,
    "eyes": 0
  },
  "timeline_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679/timeline",
  "performed_via_github_app": null,
  "state_reason": null
}
[
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1236694197",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25679#issuecomment-1236694197",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679",
    "id": 1236694197,
    "node_id": "IC_kwDOAOvK985JtnS1",
    "user": {
      "login": "s1na",
      "id": 1591639,
      "node_id": "MDQ6VXNlcjE1OTE2Mzk=",
      "avatar_url": "https://avatars.githubusercontent.com/u/1591639?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/s1na",
      "html_url": "https://github.com/s1na",
      "followers_url": "https://api.github.com/users/s1na/followers",
      "following_url": "https://api.github.com/users/s1na/following{/other_user}",
      "gists_url": "https://api.github.com/users/s1na/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/s1na/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/s1na/subscriptions",
      "organizations_url": "https://api.github.com/users/s1na/orgs",
      "repos_url": "https://api.github.com/users/s1na/repos",
      "events_url": "https://api.github.com/users/s1na/events{/privacy}",
      "received_events_url": "https://api.github.com/users/s1na/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T08:29:04Z",
    "updated_at": "2022-09-05T08:29:04Z",
    "author_association": "MEMBER",
    "body": "That might be hinting at a hardware fault. See [this explanation](https://www.reddit.com/r/ethereum/comments/wpqmo1/comment/ikrl5pz/?utm_source=share&utm_medium=web2x&context=3) by Peter.",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1236694197/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  },
  {
    "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1236740681",
    "html_url": "https://github.com/ethereum/go-ethereum/issues/25679#issuecomment-1236740681",
    "issue_url": "https://api.github.com/repos/ethereum/go-ethereum/issues/25679",
    "id": 1236740681,
    "node_id": "IC_kwDOAOvK985JtypJ",
    "user": {
      "login": "miguelmota",
      "id": 168240,
      "node_id": "MDQ6VXNlcjE2ODI0MA==",
      "avatar_url": "https://avatars.githubusercontent.com/u/168240?v=4",
      "gravatar_id": "",
      "url": "https://api.github.com/users/miguelmota",
      "html_url": "https://github.com/miguelmota",
      "followers_url": "https://api.github.com/users/miguelmota/followers",
      "following_url": "https://api.github.com/users/miguelmota/following{/other_user}",
      "gists_url": "https://api.github.com/users/miguelmota/gists{/gist_id}",
      "starred_url": "https://api.github.com/users/miguelmota/starred{/owner}{/repo}",
      "subscriptions_url": "https://api.github.com/users/miguelmota/subscriptions",
      "organizations_url": "https://api.github.com/users/miguelmota/orgs",
      "repos_url": "https://api.github.com/users/miguelmota/repos",
      "events_url": "https://api.github.com/users/miguelmota/events{/privacy}",
      "received_events_url": "https://api.github.com/users/miguelmota/received_events",
      "type": "User",
      "site_admin": false
    },
    "created_at": "2022-09-05T09:12:18Z",
    "updated_at": "2022-09-05T09:12:18Z",
    "author_association": "CONTRIBUTOR",
    "body": "it's a new 2tb ssd and I tried re-formatting to vfat and ext4 but still seem to get random errors preventing full sync. I'll keep trying",
    "reactions": {
      "url": "https://api.github.com/repos/ethereum/go-ethereum/issues/comments/1236740681/reactions",
      "total_count": 0,
      "+1": 0,
      "-1": 0,
      "laugh": 0,
      "hooray": 0,
      "confused": 0,
      "heart": 0,
      "rocket": 0,
      "eyes": 0
    },
    "performed_via_github_app": null
  }
]
